name: Publish tag
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
permissions: write-all
jobs:
  build-release-publish:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: './.github/workflows/constants.env'
          expand: true

      - name: Publish on Chrome Webstore
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7 # pin@v1
        if: "!contains(github.event.head_commit.message, '[skip chrome]')"
        with:
          workflow: publish-on-chrome-web-store
          token: ${{ secrets.WORKFLOWS_TOKEN }}

      - name: Publish on Firefox Add-ons
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7 # pin@v1
        if: "!contains(github.event.head_commit.message, '[skip firefox]')"
        with:
          workflow: publish-on-firefox-add-ons
          token: ${{ secrets.WORKFLOWS_TOKEN }}

      - name: Publish on Edge Add-ons
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7 # pin@v1
        if: "!contains(github.event.head_commit.message, '[skip edge]')"
        with:
          workflow: publish-on-edge-add-ons
          token: ${{ secrets.WORKFLOWS_TOKEN }}